### ISSUE TITLE
Problem using the theme in Github

### ISSUE THREAD

**Issue by hzambran** [bencentra/centrarium#14]
First of all, thanks for providing such an awesome theme.

I'm a newbie in Jekyll, but I think I managed already to install Jekyll (jekyll 2.5.3), gems and all the dependencies.

However, when I try to use centrarium in my 'username.github.io' page, I visualize the final web page in a pure-text format and not the beautiful them centrarium is (I also tried just forking centrarium changing the name into  'username.github.io' without good results )

The pure-text format I got is exactly what I got when running:
`jekyll build --destination web`
as you can see here:

![jekyll_build](https://cloud.githubusercontent.com/assets/2619297/10936656/c1f0aa9e-82cc-11e5-84ce-9d158d28bb4d.png)

but when I run
`jekyll serve`

in my local machine directory I got the result I want, as you can see here:
![jekyll_serve](https://cloud.githubusercontent.com/assets/2619297/10936660/ca03978c-82cc-11e5-87b0-3e7d8effe946.png)

could you provide some help in what I'm doing wrong ?

Thanks in advance

**Comment by bencentra** [comment]
Sorry for the delayed response. I noticed two things:
1) Your top-level pages are fine, but blog posts aren't. This appears to be a relative vs absolute path issue. 
2) Your repo only has the contents of `_site` instead of the whole Jekyll source files. GitHub pages are Jekyll-aware, so you can upload the whole thing and GitHub will only deploy the generated static site.

So first of all, get all your site's code onto GitHub. Then, can you share the url and baseurl properties of your `_config.yml` file? You're probably just missing one of those, or are missing a slash somewhere.

**Comment by kennmyers** [comment]
I had this problem too, solved it on mine by commenting out the baseurl property

**Comment by hzambran** [comment]
Commenting out the `baseurl` property also solved the problem in my case.

Thanks Ben for the explanation, because my limited knowledge of jekyll was hampering finding the solution you pointed out. you
