### ISSUE TITLE
category and tag can not work

### ISSUE THREAD

**Issue by maoruibin** [bencentra/centrarium#23]
[http://gudong.name/](http://gudong.name/)   this is my blog and use your theme . and now i meet a problem ,

when i click category and tag  it point 404 , I  think some place occur a problem , please give me some advice ~

 thanks~

**Comment by bencentra** [comment]
How are you hosting your blog? The jekyll-archives gem that generates the category pages is not compatible with GitHub pages. See https://github.com/github/pages-gem/issues/93. If you're hosting the website yourself, make sure the gem is installed.

**Comment by maoruibin** [comment]
I host my blog in github  [https://github.com/maoruibin/maoruibin.github.com](https://github.com/maoruibin/maoruibin.github.com) 

and in local condition click category and tag is correct ~ but when i push to Github ,it does not work ~

**Comment by bencentra** [comment]
If GitHub is the actual host of your site, categories will not work because GitHub Pages does not support the gem that generates the category pages. You'll have to disable the feature. Or submit a PR with an alternative that GitHub supports :smile:. For instance, I host my site on WebFaction: https://www.webfaction.com/

For more info, see the [README](https://github.com/bencentra/centrarium/blob/master/README.md#archive-settings)

**Comment by maoruibin** [comment]
Ok  i think i have know the problem and  thanks your advice~
